using Content.Client.UserInterface.Controls;
using Content.Shared._Nuclear14.AutodocSirius;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using System.Collections.Generic;

namespace Content.Client._Nuclear14.AutodocSirius;

[GenerateTypedNameReferences]
public sealed partial class SiriusAutodocWindow : FancyWindow
{
    private static readonly ISawmill _sawmill = Logger.GetSawmill("autodoc");
    private AutodocBoundUserInterfaceState? _lastState;

    private readonly Dictionary<string, string> _damageDisplayNames = new()
    {
        { "Blunt", "PHYSICAL" },
        { "Slash", "LACERATION" },
        { "Piercing", "PUNCTURE" },
        { "Heat", "THERMAL" },
        { "Cold", "CRYOGENIC" },
        { "Shock", "ELECTRICAL" },
        { "Caustic", "CHEMICAL" },
        { "Radiation", "RADIATION" },
        { "Bloodloss", "BLOOD LOSS" },
        { "Asphyxiation", "ASPHYXIA" },
        { "Toxin", "TOXIN" },
        { "Genetic", "GENETIC" },
        { "Cellular", "CELLULAR" }
    };

    private static readonly Color ColorMinor = Color.FromHex("#33FF33");
    private static readonly Color ColorModerate = Color.FromHex("#FFAA33");
    private static readonly Color ColorSevere = Color.FromHex("#FF5533");
    private static readonly Color ColorCritical = Color.FromHex("#FF3333");
    private static readonly Color ColorDim = Color.FromHex("#1a5c1a");
    private static readonly Color ColorActive = Color.FromHex("#33FF33");
    private static readonly Color ColorInactive = Color.FromHex("#3a5c3a");

    public event Action<AutodocUiButton>? OnAutodocButton;

    public SiriusAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        Title = "AUTODOC - SIRIUS MD-3";

        ApplyBackgroundStyles();
        WireButtons();

        EjectBeakerButton.Disabled = true;
        EjectPatientButton.Disabled = true;
        StartTreatmentButton.Disabled = true;

        EjectBeakerButton.ModulateSelfOverride = ColorInactive;
        EjectPatientButton.ModulateSelfOverride = ColorInactive;
        StartTreatmentButton.ModulateSelfOverride = ColorInactive;
    }

    private void ApplyBackgroundStyles()
    {
        BackgroundPanel.PanelOverride = new StyleBoxFlat(Color.FromHex("#0a0a0a"));
        SepTop.PanelOverride = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        SepMid1.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepMid2.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepMid3.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepBottom.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
    }

    private void WireButtons()
    {
        EjectBeakerButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectBeaker);
        EjectPatientButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectPatient);
        StartTreatmentButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.StartTreatment);
    }

    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _lastState = state;

        _sawmill.Debug($"Window UpdateState: HasBeaker={state.HasBeaker}, HasOccupant={state.HasOccupant}, IsTreating={state.IsTreating}");

        UpdatePatientInfo(state);
        UpdateDamageDisplay(state);
        UpdateStimulantsDisplay(state);
        UpdateButtonsState(state);
        UpdateErrorDisplay(state);
    }

    private void UpdatePatientInfo(AutodocBoundUserInterfaceState state)
    {
        if (state.HasOccupant && !string.IsNullOrEmpty(state.OccupantName))
        {
            PatientNameLabel.Text = state.OccupantName.ToUpperInvariant();
            PatientNameLabel.FontColorOverride = ColorActive;

            var statusText = state.OccStatus switch
            {
                OccupantStatus.Alive => "VITAL SIGNS: STABLE",
                OccupantStatus.Critical => "VITAL SIGNS: CRITICAL",
                OccupantStatus.Dead => "VITAL SIGNS: NONE - DECEASED",
                _ => "STATUS: UNKNOWN"
            };

            StatusLabel.Text = statusText;
            StatusLabel.FontColorOverride = state.OccStatus switch
            {
                OccupantStatus.Alive => ColorMinor,
                OccupantStatus.Critical => ColorModerate,
                OccupantStatus.Dead => ColorCritical,
                _ => ColorDim
            };
        }
        else
        {
            PatientNameLabel.Text = "NO PATIENT";
            PatientNameLabel.FontColorOverride = ColorDim;
            StatusLabel.Text = "AWAITING SUBJECT";
            StatusLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateDamageDisplay(AutodocBoundUserInterfaceState state)
    {
        DamageContainer.RemoveAllChildren();

        if (!state.HasOccupant || state.OccupantDamage == null || state.OccupantDamage.Count == 0)
        {
            var emptyLabel = MakeDiagnosticLine("NO DAMAGE DETECTED", ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }

        var sortedDamage = new List<KeyValuePair<string, FixedPoint2>>(state.OccupantDamage);
        sortedDamage.Sort((a, b) => b.Value.Float().CompareTo(a.Value.Float()));

        foreach (var damage in sortedDamage)
        {
            var damageType = damage.Key;
            var amount = damage.Value.Float();

            if (amount <= 0) continue;

            var displayName = GetDamageDisplayName(damageType);
            var color = GetDamageColor(amount);

            var line = MakeDamageLine(displayName, amount, color);
            DamageContainer.AddChild(line);
        }
    }

    private BoxContainer MakeDamageLine(string damageName, float amount, Color color)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };

        var nameLabel = new Label
        {
            Text = $"[ {damageName} ]",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 140
        };

        var barBg = new PanelContainer
        {
            MinWidth = 120,
            MinHeight = 12,
            HorizontalExpand = false,
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1a3a1a") }
        };

        var barWidth = MathHelper.Clamp(amount / 100f, 0.05f, 1f);
        var fillWidth = 120f * barWidth;
        var fillPanel = new PanelContainer
        {
            MinWidth = fillWidth,
            MinHeight = 12,
            PanelOverride = new StyleBoxFlat { BackgroundColor = color }
        };

        barBg.AddChild(fillPanel);

        var amountLabel = new Label
        {
            Text = $"{amount:F0}%",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Right
        };

        container.AddChild(nameLabel);
        container.AddChild(barBg);
        container.AddChild(amountLabel);

        return container;
    }

    private Label MakeDiagnosticLine(string text, Color color)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 8, 0, 8)
        };
    }

    private string GetDamageDisplayName(string damageType)
    {
        return _damageDisplayNames.GetValueOrDefault(damageType, damageType.ToUpperInvariant());
    }

    private Color GetDamageColor(float amount)
    {
        if (amount >= 75) return ColorCritical;
        if (amount >= 50) return ColorSevere;
        if (amount >= 25) return ColorModerate;
        if (amount > 0) return ColorMinor;
        return ColorDim;
    }

    private void UpdateStimulantsDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.HasBeaker)
        {
            var amount = state.BeakerStimulantsAmount.Float();
            StimulantsLabel.Text = $"{amount:F1}";
            StimulantsLabel.FontColorOverride = amount >= 30 ? ColorMinor : ColorModerate;
        }
        else
        {
            StimulantsLabel.Text = "NONE";
            StimulantsLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateButtonsState(AutodocBoundUserInterfaceState state)
    {
        var ejectBeakerDisabled = !state.HasBeaker || state.IsTreating;
        var ejectPatientDisabled = !state.HasOccupant || state.IsTreating;
        var startDisabled = !state.TreatButtonEnabled || state.IsTreating;

        _sawmill.Debug($"UpdateButtonsState: ejectBeakerDisabled={ejectBeakerDisabled} (HasBeaker={state.HasBeaker}), " +
                       $"ejectPatientDisabled={ejectPatientDisabled} (HasOccupant={state.HasOccupant}), " +
                       $"startDisabled={startDisabled} (TreatButtonEnabled={state.TreatButtonEnabled})");

        EjectBeakerButton.Disabled = ejectBeakerDisabled;
        EjectPatientButton.Disabled = ejectPatientDisabled;
        StartTreatmentButton.Disabled = startDisabled;

        EjectBeakerButton.ModulateSelfOverride = ejectBeakerDisabled ? ColorInactive : null;
        EjectPatientButton.ModulateSelfOverride = ejectPatientDisabled ? ColorInactive : null;
        StartTreatmentButton.ModulateSelfOverride = startDisabled ? ColorInactive : null;

        if (state.IsTreating)
        {
            StartTreatmentButton.Text = "[ TREATMENT IN PROGRESS ]";
        }
        else
        {
            StartTreatmentButton.Text = "[ START TREATMENT ]";
        }
    }

    private void UpdateErrorDisplay(AutodocBoundUserInterfaceState state)
    {
        var hasError = !string.IsNullOrEmpty(state.ErrorMessage);
        ErrorLabel.Visible = hasError;

        if (hasError && state.ErrorMessage != null)
        {
            ErrorLabel.Text = state.ErrorMessage.ToUpperInvariant();
        }
    }
}
